### ISSUE TITLE
NPE in EiraIRC ChannelChatEvent handler

### ISSUE THREAD

**Issue by blay09** [Lordmau5/The-Kappa-Experience#3]
EiraIRC continues to stay connected to IRC even after leaving a world if the persistentConnection option is enabled, causing the IRCChannelChatEvent to be fired even when not currently in a world.
I assume whatever is causing the NPE is something that's only available when a world is loaded.

[19:02:00] [IRC (irc.twitch.tv)/ERROR] [FML/]: Exception caught during firing event net.blay09.mods.eirairc.api.event.IRCChannelChatEvent@7e696fd7:
java.lang.NullPointerException
	at com.lordmau5.kappaexperience.compatibility.AddonEventHandler.eiraIRCEvent(AddonEventHandler.java:67) ~[AddonEventHandler.class:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_795_AddonEventHandler_eiraIRCEvent_IRCChannelChatEvent.invoke(.dynamic) ~[?:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:?]
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138) [EventBus.class:?]
	at net.blay09.mods.eirairc.irc.IRCConnectionImpl.handleMessage(IRCConnectionImpl.java:381) [IRCConnectionImpl.class:?]
	at net.blay09.mods.eirairc.irc.IRCConnectionImpl.run(IRCConnectionImpl.java:189) [IRCConnectionImpl.class:?]

**Comment by Lordmau5** [comment]
Fixed with a null-check (EntityPlayer was null)
